# CHANGEME (replace "drupalproj" with project shortcode).
name: drupalproj
recipe: drupal8

services:
  appserver:
    xdebug: true
    # The following additional build step will install the Platform CLI in the
    # application container.
    #build:
    #  - "curl -sS https://platform.sh/cli/installer | php"
  node:
    # Optionally specify the version to match that of the hosting provider.
    type: node
    build:
      - "cd $LANDO_MOUNT && npm it"
  pma:
    # Use the latest version of phpmyadmin
    type: phpmyadmin

tooling:
  npm:
    service: node
  node:
    service: node
  # The following entry creates a `lando platform` command that will run
  # any Platform CLI command from inside the container if desired.
#  platform:
#    service: appserver
#    description: Run Platform CLI commands
#    cmd:
#      - /var/www/.platformsh/bin/platform
#    options:
#      passthrough: true

config:
  # Lando defaults to Apache. Switch to nginx to match hosting provider.
  via: nginx

  # Set the webroot.
  webroot: web

  # Lando defaults to the latest MySQL release, but most hosting uses MariaDB.
  # Specify the version to match what's in services.yaml.
  database: mariadb:10.1
