#!/bin/bash -e

ROOT=$(pwd)
DRUSH=$ROOT/vendor/bin/drush
VERSION=${1:-drupal-8}
DRUPAL_TEMP=$(mktemp -d)

$DRUSH dl "$VERSION" --root=$DRUPAL_TEMP --destination=$DRUPAL_TEMP --drupal-project-rename=drupal-8 --quiet -y

rsync -avz --delete $DRUPAL_TEMP/drupal-8/ "$ROOT/web" \
 --exclude=.gitkeep \
 --exclude=autoload.php \
 --exclude=composer.json \
 --exclude=composer.lock \
 --exclude=core \
 --exclude=drush \
 --exclude=example.gitignore \
 --exclude=LICENSE.txt \
 --exclude=README.txt \
 --exclude=vendor \
 --exclude=sites \
 --exclude=themes \
 --exclude=profiles \
 --exclude=modules

rm -rf $DRUPAL_TEMP/drupal-8
